In [1]:
import csv
import time
import numpy as np
import torch
import pytorch_lightning as pl
from sklearn.preprocessing import StandardScaler
from chemprop.v2 import data
from chemprop.v2 import featurizers
from chemprop.v2.models import modules, models

In [2]:
from pytorch_lightning.callbacks.progress import ProgressBar, RichProgressBar, TQDMProgressBar
import sys
class MyProgressBar(TQDMProgressBar):
    def init_validation_tqdm(self):
        bar = super().init_validation_tqdm()
        if not sys.stdout.isatty():
            bar.disable = True
        return bar

    def init_predict_tqdm(self):
        bar = super().init_predict_tqdm()
        if not sys.stdout.isatty():
            bar.disable = True
        return bar

    def init_test_tqdm(self):
        bar = super().init_test_tqdm()
        if not sys.stdout.isatty():
            bar.disable = True
        return bar

In [ ]:
# checkpoint = torch.load('/home/gridsan/nmorgan/chemprop/nathan/lightning_logs/version_23666795/checkpoints/epoch=199-step=200.ckpt', map_location=torch.device('cpu'))
# checkpoint

In [3]:
molenc_chk = modules.molecule_block()
models = models.RegressionMPNN.load_from_checkpoint('/home/gridsan/nmorgan/chemprop/nathan/lightning_logs/version_23666795/checkpoints/epoch=199-step=200.ckpt', mpn_block = molenc_chk,  map_location=torch.device("cpu"))
   

In [4]:
with open("/home/gridsan/nmorgan/MW_smi.csv") as fid:
    reader = csv.reader(fid)
    next(reader)
    smis = [smi[0] for smi in reader]

featurizer = featurizers.MoleculeFeaturizer()

pred_smis = [data.MoleculeDatapoint(smi) for smi in smis]
pred_dset = data.MoleculeDataset(pred_smis, featurizer)
pred_loader = data.MolGraphDataLoader(pred_dset, num_workers=4, shuffle=False)

In [6]:
trainer = pl.Trainer()
output = trainer.predict(models, pred_loader)

/home/gridsan/nmorgan/mambaforge/envs/chemprop_gpu/lib/python3.11/site-packages/lightning_fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/gridsan/nmorgan/mambaforge/envs/chemprop_gpu/l ...
  rank_zero_warn(
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


/home/gridsan/nmorgan/mambaforge/envs/chemprop_gpu/lib/python3.11/site-packages/lightning_fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /home/gridsan/nmorgan/mambaforge/envs/chemprop_gpu/l ...
  rank_zero_warn(


Predicting DataLoader 0: 100%|██████████| 100/100 [00:07<00:00, 13.60it/s]


In [7]:
output

[(tensor([[138.2337]]), None),
 (tensor([[190.9051]]), None),
 (tensor([[435.3252]]), None),
 (tensor([[120.3308]]), None),
 (tensor([[67.6199]]), None),
 (tensor([[130.6288]]), None),
 (tensor([[67.6199]]), None),
 (tensor([[146.2285]]), None),
 (tensor([[163.4315]]), None),
 (tensor([[60.3734]]), None),
 (tensor([[399.9455]]), None),
 (tensor([[381.2084]]), None),
 (tensor([[135.3354]]), None),
 (tensor([[148.1225]]), None),
 (tensor([[111.7454]]), None),
 (tensor([[120.2314]]), None),
 (tensor([[187.9702]]), None),
 (tensor([[122.7746]]), None),
 (tensor([[33.7348]]), None),
 (tensor([[84.4824]]), None),
 (tensor([[172.4203]]), None),
 (tensor([[67.9176]]), None),
 (tensor([[120.3083]]), None),
 (tensor([[131.3990]]), None),
 (tensor([[281.1966]]), None),
 (tensor([[127.0592]]), None),
 (tensor([[175.6653]]), None),
 (tensor([[81.1315]]), None),
 (tensor([[246.2979]]), None),
 (tensor([[62.3632]]), None),
 (tensor([[204.4761]]), None),
 (tensor([[121.3655]]), None),
 (tensor([[159.9

In [7]:
molenc_chk = modules.molecule_block()
n_tasks = checkpoint['hyper_parameters']['n_tasks']
mpnn_chk = models.RegressionMPNN(mpn_block = molenc_chk, n_tasks = n_tasks)
mpnn_chk.load_state_dict(checkpoint['state_dict'])
mpnn_chk.scaler = checkpoint['hyper_parameters']['scaler']

In [1]:
import argparse

In [5]:
obj = argparse._ActionsContainer(None, '-', None, 'error')

In [7]:
obj.register()

TypeError: _ActionsContainer.register() missing 3 required positional arguments: 'registry_name', 'value', and 'object'